version: '2'
services:
  rs1_srv2:
    image: mongo:3.2
    command: mongod --dbpath /data/db --replSet "rs0" --noprealloc --smallfiles --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/rs1_srv2:/data/db
    logging:
      options:
        max-size: 25k
      
  rs1_srv1:
    image: mongo:3.2
    command: mongod --dbpath /data/db --replSet "rs0" --noprealloc --smallfiles --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/rs1_srv1:/data/db
    logging:
      options:
        max-size: 15k
    
  configsvr1:
    image: mongo:3.2
    command: mongod --dbpath /data/db --configsvr --replSet configReplSet --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/configsvr1:/data/db
    
  configsvr2:
    image: mongo:3.2
    command: mongod --dbpath /data/db --configsvr --replSet configReplSet --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/configsvr2:/data/db

  configsvr3:
    image: mongo:3.2
    command: mongod --dbpath /data/db --configsvr --replSet configReplSet --port 27017 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/configsvr3:/data/db

  router1:
    image: mongo:3.2
    ports:
      - "127.0.0.1:27017:27017"
    command: mongos --configdb configReplSet/configsvr1:27017,configsvr2:27017,configsvr3:27017 --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
    
  router2:
    image: mongo:3.2
    ports:
      - "127.0.0.1:27018:27017"
    command: mongos --configdb configReplSet/configsvr1:27017,configsvr2:27017,configsvr3:27017 --port 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro